# Context: - a Set of predefined objects or variables that contain information about a workflow run.
#          - contain infromation about the environmments, events, jobs, steps, and various other options.
#          - each context is an object that contain properties, which can be a string or some other objects that can be accessed from within the workflow.


name: Context testing
on: push

jobs: 
    dump_contexts_to_log:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env: 
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump job context
              env: 
                GITHUB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"
            - name: Dump steps context
              env: 
                GITHUB_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"
            - name: Dump runner context
              env: 
                GITHUB_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
            - name: Dump secret context
              env: 
                GITHUB_CONTEXT: ${{ toJson(secrets) }}
              run: echo "$SECRET_CONTEXT"