name: Matrix Configuration

on: 
    push:
    workflow_dispatch: 

##############deploying the same job on different OS or versions ###############################

#jobs: 
#    deploy-on-ubuntu:
#        runs-on: ubuntu-latest
#        steps:
#            - name: Echo Docker Details
#              run: docker info
#
#            - name: Run Images
#              run: docker run hello-world
#
#
#    deploy-on-windows:
#        runs-on: windows-latest
#        steps:
#            - name: Echo Docker Details
#              run: docker info
#
#            - name: Run Images
#              run: docker run hello-world
#

####################running same task on different os or version using single job ################

jobs: 
    deploy:
        strategy:
            fail-fast: false    # to ensure jobs in queue/running in parallel are not cancelled when a job fails
            max-parallel: 2     # limit the number of jobs running in parallel
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
                exclude:                # to exclude specific configurations defined in the matrix.
                    - images: alpine    # alpine does not run on windows os
                      os: windows-latest
                include:
                    - images: amd64/alpine
                      os: ubuntu-20.04
        runs-on: ${{ matrix.os}}
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Images on ${{ matrix.os}}
              run: docker run ${{ matrix.images}}